Design Entry;SmartDesign Check||(null)||'CD3FF' was generated successfully||Open datasheet;liberoaction://open_report/file/CD3FF_DataSheet.xml||(null);(null)
HelpInfo,C:\Microsemi\Libero_SoC_v11.8\SynplifyPro\lib\html,fpgahelp.qhc,errormessages.mp,C:\Microsemi\Libero_SoC_v11.8\SynplifyPro\bin\mbin\assistant
Implementation;Compile;RootName:CD3FF
Implementation;Compile||(null)||Please refer to the log file for details about 1 Info(s)||CD3FF_compile_log.rpt;liberoaction://open_report/file/CD3FF_compile_log.rpt||(null);(null)
Implementation;Place and Route||OnlineHelp;liberoaction://open_online_help/98304003||Info: I/O Bank Assigner detected (1) out of (6) I/O Bank(s) with locked I/O technologies.||(null);(null)||(null);(null)
Implementation;Place and Route;RootName:CD3FF
Implementation;Place and Route||(null)||Please refer to the log file for details about 2 Info(s)||CD3FF_placeroute_log.rpt;liberoaction://open_report/file/CD3FF_placeroute_log.rpt||(null);(null)
