HelpInfo,C:\Microsemi\Libero_SoC_v11.8\SynplifyPro\lib\html,fpgahelp.qhc,errormessages.mp,C:\Microsemi\Libero_SoC_v11.8\SynplifyPro\bin\mbin\assistant
Implementation;Synthesis;RootName:Counter
Implementation;Synthesis|| MT530 ||@W:Found inferred clock Counter|CLK which controls 16 sequential elements including count[15:0]. This clock has no specified timing constraint which may adversely impact design performance. ||Counter.srr(100);liberoaction://cross_probe/hdl/file/'C:\Microsemi_Prj\hw7\Counter\synthesis\Counter.srr'/linenumber/100||counter.vhd(44);liberoaction://cross_probe/hdl/file/'c:\microsemi_prj\hw7\counter\hdl\counter.vhd'/linenumber/44
Implementation;Synthesis|| MT420 ||@W:Found inferred clock Counter|CLK with period 10.00ns. Please declare a user-defined clock on object "p:CLK"||Counter.srr(225);liberoaction://cross_probe/hdl/file/'C:\Microsemi_Prj\hw7\Counter\synthesis\Counter.srr'/linenumber/225||null;null
Implementation;Synthesis|| MT320 ||@N: This timing report is an estimate of place and route data. For final timing results, use the FPGA vendor place and route report.||Counter.srr(241);liberoaction://cross_probe/hdl/file/'C:\Microsemi_Prj\hw7\Counter\synthesis\Counter.srr'/linenumber/241||null;null
Implementation;Synthesis|| MT322 ||@N: Clock constraints include only register-to-register paths associated with each individual clock.||Counter.srr(243);liberoaction://cross_probe/hdl/file/'C:\Microsemi_Prj\hw7\Counter\synthesis\Counter.srr'/linenumber/243||null;null
Implementation;Compile;RootName:Counter
Implementation;Compile||(null)||Please refer to the log file for details||Counter_compile_log.rpt;liberoaction://open_report/file/Counter_compile_log.rpt||(null);(null)
Implementation;Place and Route||OnlineHelp;liberoaction://open_online_help/98304003||Info: I/O Bank Assigner detected (1) out of (6) I/O Bank(s) with locked I/O technologies.||(null);(null)||(null);(null)
Implementation;Place and Route;RootName:Counter
Implementation;Place and Route||(null)||Please refer to the log file for details about 2 Info(s)||Counter_placeroute_log.rpt;liberoaction://open_report/file/Counter_placeroute_log.rpt||(null);(null)
