Implementation;Compile;RootName:fifo2x8
Implementation;Compile||(null)||Please refer to the log file for details about 1 Warning(s) , 1 Info(s)||fifo2x8_compile_log.rpt;liberoaction://open_report/file/fifo2x8_compile_log.rpt||(null);(null)
HelpInfo,C:\Microsemi\Libero_SoC_v11.8\SynplifyPro\lib\html,fpgahelp.qhc,errormessages.mp,C:\Microsemi\Libero_SoC_v11.8\SynplifyPro\bin\mbin\assistant
Implementation;Synthesis;RootName:fifo2x8
Implementation;Synthesis|| MT116 ||@W:Paths from clock (fifo2x8|clk2:r) to clock (fifo2x8|clk1:r) are overconstrained because the required time of 5.00 ns is too small.  ||fifo2x8.srr(289);liberoaction://cross_probe/hdl/file/'C:\Microsemi_Prj\hw9\p2\synthesis\fifo2x8.srr'/linenumber/289||null;null
Implementation;Synthesis|| MT116 ||@W:Paths from clock (fifo2x8|clk1:r) to clock (fifo2x8|clk2:r) are overconstrained because the required time of 5.00 ns is too small.  ||fifo2x8.srr(290);liberoaction://cross_probe/hdl/file/'C:\Microsemi_Prj\hw9\p2\synthesis\fifo2x8.srr'/linenumber/290||null;null
