HelpInfo,C:\Microsemi\Libero_SoC_v11.8\SynplifyPro\lib\html,fpgahelp.qhc,errormessages.mp,C:\Microsemi\Libero_SoC_v11.8\SynplifyPro\bin\mbin\assistant
Implementation;Synthesis;RootName:Skewed
Implementation;Synthesis|| MT530 ||@W:Found inferred clock Skewed|clk which controls 16 sequential elements including q[15:0]. This clock has no specified timing constraint which may adversely impact design performance. ||Skewed.srr(105);liberoaction://cross_probe/hdl/file/'C:\Microsemi_Prj\hw7\p3\Skewed\synthesis\Skewed.srr'/linenumber/105||skewed.v(29);liberoaction://cross_probe/hdl/file/'c:\microsemi_prj\hw7\p3\skewed\hdl\skewed.v'/linenumber/29
Implementation;Synthesis|| MT420 ||@W:Found inferred clock Skewed|clk with period 10.00ns. Please declare a user-defined clock on object "p:clk"||Skewed.srr(230);liberoaction://cross_probe/hdl/file/'C:\Microsemi_Prj\hw7\p3\Skewed\synthesis\Skewed.srr'/linenumber/230||null;null
Implementation;Synthesis|| MT320 ||@N: This timing report is an estimate of place and route data. For final timing results, use the FPGA vendor place and route report.||Skewed.srr(246);liberoaction://cross_probe/hdl/file/'C:\Microsemi_Prj\hw7\p3\Skewed\synthesis\Skewed.srr'/linenumber/246||null;null
Implementation;Synthesis|| MT322 ||@N: Clock constraints include only register-to-register paths associated with each individual clock.||Skewed.srr(248);liberoaction://cross_probe/hdl/file/'C:\Microsemi_Prj\hw7\p3\Skewed\synthesis\Skewed.srr'/linenumber/248||null;null
Implementation;Compile;RootName:Skewed
Implementation;Compile||(null)||Please refer to the log file for details||Skewed_compile_log.rpt;liberoaction://open_report/file/Skewed_compile_log.rpt||(null);(null)
Implementation;Place and Route||OnlineHelp;liberoaction://open_online_help/98304003||Info: I/O Bank Assigner detected (1) out of (6) I/O Bank(s) with locked I/O technologies.||(null);(null)||(null);(null)
Implementation;Place and Route;RootName:Skewed
Implementation;Place and Route||(null)||Please refer to the log file for details about 2 Info(s)||Skewed_placeroute_log.rpt;liberoaction://open_report/file/Skewed_placeroute_log.rpt||(null);(null)
